# Book settings
title: "Data Analytics for Chemical Engineers"
author: "A.J. Medford"
#logo: "images/logo.png"

only_build_toc_files: true

exclude_patterns:
  - "_build"
  - "_trash"
  - "**/.ipynb_checkpoints"
  - ".venv"
  - ".venv/**"
  - "venv"
  - "venv/**"
  - "env"
  - "env/**"
  - "**/site-packages/**"
  - "node_modules"
  - "node_modules/**"

# Execution settings
execute:
  execute_notebooks: "auto" # or force or off
  timeout: 600
  cache: "default"
  cache_path: _exec_cache
  in_temp: false
  allow_errors: false

# Enable notebook downloads (.ipynb)
mystnb:
  notebooks_download: true

# Launch buttons (optional, for Binder or JupyterHub)
#launch_buttons:
#  notebook_interface: classic
#  binderhub_url: "https://mybinder.org"
#  thebe: false

# HTML-specific options
html:
#  favicon: "images/favicon.ico"
  navbar_number_sections: true
#  use_edit_page_button: true
  extra_navbar: ""
  extra_footer: "© 2025 A.J. Medford"
  home_page_in_navbar: true
  baseurl: ""

# Add custom CSS or JS if needed
#extra_css:
#  - custom.css
